name: matan_calendar
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  go_router: ^6.0.0
  bot_toast: ^4.0.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.1.0
  flutter_riverpod: ^2.2.0
  riverpod_generator: ^1.2.0
  syncfusion_flutter_datepicker: ^20.4.52
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
# use this command for Freezed: flutter pub run build_runner build
#                               flutter packages pub run build_runner build --delete-conflicting-outputs
